POST http://localhost:3001/api/oinks
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbGxlX2thbGExIiwiaWQiOiIyMGIwZTI1NC1kODNlLTQ0YzUtOGU4MC1lZGNjNGI3NWJiNGYiLCJpYXQiOjE2MDAwMDY2Mjh9.xf4NpjNfFAXoVBzVPuxcFEFOrwJ8pW99vtlcW8HElQk

{
    "content": "This is so cool"
}