POST http://localhost:3001/api/oinks/like/ee92ca77-2999-4aa7-bfbc-ff00b2fe64cc
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJvcnNhcyIsImlkIjoiZGNjOWVlNTYtMWYwMy00YTVkLWI3ZGItMGYzNmQxMjlhOTE3IiwiaWF0IjoxNTk5NTAzNTgyfQ.FernRUqzoHqAZUwlBqHAGytPv4q847wCQ7DnQEnlOAU

