POST http://localhost:3001/api/user/follow/8187dc7c-4747-4ca5-b127-9c2828897898
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbGxlX2thbGExIiwiaWQiOiI4MTg3ZGM3Yy00NzQ3LTRjYTUtYjEyNy05YzI4Mjg4OTc4OTgiLCJpYXQiOjE2MDAwOTk3NDh9.c-tbCrYG_0wR780j_omM5YSqug6qyarMCHKy6tA4iao
