POST http://localhost:3001/api/oinks/like/563d33b7-40f1-4b4d-8aee-2a04123465b3
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkthbGxlX2thbGExIiwiaWQiOiI4MTg3ZGM3Yy00NzQ3LTRjYTUtYjEyNy05YzI4Mjg4OTc4OTgiLCJpYXQiOjE2MDAxMDI1Nzh9.1ox65zVwOaMpIdCb2yYjlkT4J8R6nbGHwG5aucfPoM8

